package edu.mum.cs545.entity;
// Generated Dec 10, 2015 8:59:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer id;
     private Role role;
     private String firstname;
     private String lastname;
     private String username;
     private String password;
     private String status;
     private Set<UserStory> userStoriesForDeveloperId = new HashSet<UserStory>(0);
     private Set<Product> products = new HashSet<Product>(0);
     private Set<UserStory> userStoriesForTestId = new HashSet<UserStory>(0);
     private Set<UserStory> userStoriesForOwnerId = new HashSet<UserStory>(0);

    public Employee() {
    }

    public Employee(Role role, String firstname, String lastname, String username, String password, String status, Set<UserStory> userStoriesForDeveloperId, Set<Product> products, Set<UserStory> userStoriesForTestId, Set<UserStory> userStoriesForOwnerId) {
       this.role = role;
       this.firstname = firstname;
       this.lastname = lastname;
       this.username = username;
       this.password = password;
       this.status = status;
       this.userStoriesForDeveloperId = userStoriesForDeveloperId;
       this.products = products;
       this.userStoriesForTestId = userStoriesForTestId;
       this.userStoriesForOwnerId = userStoriesForOwnerId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<UserStory> getUserStoriesForDeveloperId() {
        return this.userStoriesForDeveloperId;
    }
    
    public void setUserStoriesForDeveloperId(Set<UserStory> userStoriesForDeveloperId) {
        this.userStoriesForDeveloperId = userStoriesForDeveloperId;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }
    public Set<UserStory> getUserStoriesForTestId() {
        return this.userStoriesForTestId;
    }
    
    public void setUserStoriesForTestId(Set<UserStory> userStoriesForTestId) {
        this.userStoriesForTestId = userStoriesForTestId;
    }
    public Set<UserStory> getUserStoriesForOwnerId() {
        return this.userStoriesForOwnerId;
    }
    
    public void setUserStoriesForOwnerId(Set<UserStory> userStoriesForOwnerId) {
        this.userStoriesForOwnerId = userStoriesForOwnerId;
    }




}


