package edu.mum.cs545.entity;
// Generated Dec 10, 2015 8:59:05 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

    private Integer id;
    private Employee employee;
    private Status status;
    private String name;
    private Date startDate;
    private Date dueDate;
    private String description;
    private Set<ReleaseBacklog> releaseBacklogs = new HashSet<ReleaseBacklog>(0);
    private Set<UserStory> userStories = new HashSet<UserStory>(0);

    public Product() {
    }

    public Product(Employee employee) {
        this.employee = employee;
    }

    public Product(Employee employee, Status status, String name, Date startDate, Date dueDate, String description, Set<ReleaseBacklog> releaseBacklogs, Set<UserStory> userStories) {
        this.employee = employee;
        this.status = status;
        this.name = name;
        this.startDate = startDate;
        this.dueDate = dueDate;
        this.description = description;
        this.releaseBacklogs = releaseBacklogs;
        this.userStories = userStories;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getDueDate() {
        return this.dueDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<ReleaseBacklog> getReleaseBacklogs() {
        return this.releaseBacklogs;
    }

    public void setReleaseBacklogs(Set<ReleaseBacklog> releaseBacklogs) {
        this.releaseBacklogs = releaseBacklogs;
    }

    public Set<UserStory> getUserStories() {
        return this.userStories;
    }

    public void setUserStories(Set<UserStory> userStories) {
        this.userStories = userStories;
    }

}
