package edu.mum.cs545.entity;
// Generated Dec 10, 2015 8:59:05 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ReleaseBacklog generated by hbm2java
 */
public class ReleaseBacklog  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private String name;
     private String type;
     private Date startDate;
     private Date dueDate;
     private String descriptioon;
     private Integer scrumMasterId;

    public ReleaseBacklog() {
    }

	
    public ReleaseBacklog(Product product) {
        this.product = product;
    }
    public ReleaseBacklog(Product product, String name, String type, Date startDate, Date dueDate, String descriptioon, Integer scrumMasterId) {
       this.product = product;
       this.name = name;
       this.type = type;
       this.startDate = startDate;
       this.dueDate = dueDate;
       this.descriptioon = descriptioon;
       this.scrumMasterId = scrumMasterId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public String getDescriptioon() {
        return this.descriptioon;
    }
    
    public void setDescriptioon(String descriptioon) {
        this.descriptioon = descriptioon;
    }
    public Integer getScrumMasterId() {
        return this.scrumMasterId;
    }
    
    public void setScrumMasterId(Integer scrumMasterId) {
        this.scrumMasterId = scrumMasterId;
    }




}


