package edu.mum.cs545.entity;
// Generated Dec 10, 2015 8:59:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sprint generated by hbm2java
 */
public class Sprint  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Date startDate;
     private Date dueDate;
     private int releaseId;
     private Set<UserStory> userStories = new HashSet<UserStory>(0);

    public Sprint() {
    }

	
    public Sprint(int releaseId) {
        this.releaseId = releaseId;
    }
    public Sprint(String name, Date startDate, Date dueDate, int releaseId, Set<UserStory> userStories) {
       this.name = name;
       this.startDate = startDate;
       this.dueDate = dueDate;
       this.releaseId = releaseId;
       this.userStories = userStories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public int getReleaseId() {
        return this.releaseId;
    }
    
    public void setReleaseId(int releaseId) {
        this.releaseId = releaseId;
    }
    public Set<UserStory> getUserStories() {
        return this.userStories;
    }
    
    public void setUserStories(Set<UserStory> userStories) {
        this.userStories = userStories;
    }




}


