package edu.mum.cs545.entity;
// Generated Dec 10, 2015 8:59:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserStory generated by hbm2java
 */
public class UserStory  implements java.io.Serializable {


     private Integer id;
     private Employee employeeByDeveloperId;
     private Employee employeeByTestId;
     private Employee employeeByOwnerId;
     private Product product;
     private Sprint sprint;
     private String name;
     private String priority;
     private Date startDate;
     private Date dueDate;
     private Integer estimateDevEffort;
     private Integer estimateTestEffort;
     private String description;
     private Integer releaseId;
     private Set<Worklog> worklogs = new HashSet<Worklog>(0);

    public UserStory() {
    }

	
    public UserStory(Employee employeeByOwnerId, Product product) {
        this.employeeByOwnerId = employeeByOwnerId;
        this.product = product;
    }
    public UserStory(Employee employeeByDeveloperId, Employee employeeByTestId, Employee employeeByOwnerId, Product product, Sprint sprint, String name, String priority, Date startDate, Date dueDate, Integer estimateDevEffort, Integer estimateTestEffort, String description, Integer releaseId, Set<Worklog> worklogs) {
       this.employeeByDeveloperId = employeeByDeveloperId;
       this.employeeByTestId = employeeByTestId;
       this.employeeByOwnerId = employeeByOwnerId;
       this.product = product;
       this.sprint = sprint;
       this.name = name;
       this.priority = priority;
       this.startDate = startDate;
       this.dueDate = dueDate;
       this.estimateDevEffort = estimateDevEffort;
       this.estimateTestEffort = estimateTestEffort;
       this.description = description;
       this.releaseId = releaseId;
       this.worklogs = worklogs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Employee getEmployeeByDeveloperId() {
        return this.employeeByDeveloperId;
    }
    
    public void setEmployeeByDeveloperId(Employee employeeByDeveloperId) {
        this.employeeByDeveloperId = employeeByDeveloperId;
    }
    public Employee getEmployeeByTestId() {
        return this.employeeByTestId;
    }
    
    public void setEmployeeByTestId(Employee employeeByTestId) {
        this.employeeByTestId = employeeByTestId;
    }
    public Employee getEmployeeByOwnerId() {
        return this.employeeByOwnerId;
    }
    
    public void setEmployeeByOwnerId(Employee employeeByOwnerId) {
        this.employeeByOwnerId = employeeByOwnerId;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Sprint getSprint() {
        return this.sprint;
    }
    
    public void setSprint(Sprint sprint) {
        this.sprint = sprint;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public Integer getEstimateDevEffort() {
        return this.estimateDevEffort;
    }
    
    public void setEstimateDevEffort(Integer estimateDevEffort) {
        this.estimateDevEffort = estimateDevEffort;
    }
    public Integer getEstimateTestEffort() {
        return this.estimateTestEffort;
    }
    
    public void setEstimateTestEffort(Integer estimateTestEffort) {
        this.estimateTestEffort = estimateTestEffort;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getReleaseId() {
        return this.releaseId;
    }
    
    public void setReleaseId(Integer releaseId) {
        this.releaseId = releaseId;
    }
    public Set<Worklog> getWorklogs() {
        return this.worklogs;
    }
    
    public void setWorklogs(Set<Worklog> worklogs) {
        this.worklogs = worklogs;
    }




}


