package edu.mum.cs545.entity;
// Generated Dec 10, 2015 8:59:05 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Worklog generated by hbm2java
 */
public class Worklog  implements java.io.Serializable {


     private Integer id;
     private UserStory userStory;
     private Integer actualEffort;
     private Date modifiedDate;
     private String effortType;

    public Worklog() {
    }

	
    public Worklog(UserStory userStory) {
        this.userStory = userStory;
    }
    public Worklog(UserStory userStory, Integer actualEffort, Date modifiedDate, String effortType) {
       this.userStory = userStory;
       this.actualEffort = actualEffort;
       this.modifiedDate = modifiedDate;
       this.effortType = effortType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UserStory getUserStory() {
        return this.userStory;
    }
    
    public void setUserStory(UserStory userStory) {
        this.userStory = userStory;
    }
    public Integer getActualEffort() {
        return this.actualEffort;
    }
    
    public void setActualEffort(Integer actualEffort) {
        this.actualEffort = actualEffort;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getEffortType() {
        return this.effortType;
    }
    
    public void setEffortType(String effortType) {
        this.effortType = effortType;
    }




}


